server:
  # Response data gzip.
  forward-headers-strategy: native
  compression:
    enabled: false
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: postgres://raotnlvoooxvqa:97ad9721ed6c7ac8d4b21ab93629b1c7c84fc3f6fe1e977687fea8d4a34d16b0@ec2-54-198-213-75.compute-1.amazonaws.com:5432/d2jcc24i0l7jer?ssl=false&sslfactory=org.postgresql.ssl.NonValidatingFactory&characterEncoding=utf8&serverTimezone=GMT%2B8
    username: raotnlvoooxvqa
    password: 97ad9721ed6c7ac8d4b21ab93629b1c7c84fc3f6fe1e977687fea8d4a34d16b0


  
halo:
  # Your admin client path is https://your-domain/{admin-path}
  admin-path: admin
  doc-disabled: true
  production-env: true
  auth-enabled: true
  mode: production
  workDir: ${user.home}/genhub-prod/
  cache: level
  ipv4DataPath: ip2locationdb/IP2LOCATION-LITE-DB11.BIN
  ipv6DataPath: 
