server:
  port: 8090
  connection-timeout: 50000
  forward-headers-strategy: native
  compression:
    enabled: true
    mime-types: text/html,text/css,application/javascript,application/json,text/plain
    min-response-size: 1024
  http2:
    enabled: true
spring:
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
  devtools:
    add-properties: false
  output:
    ansi:
      enabled: always
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
  profiles:
    active: dev

  h2:
    console:
      settings:
        web-allow-others: false
      path: /h2-console
      enabled: false
  jpa:
    hibernate:
      ddl-auto: update
      naming:
          physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    enabled: false
  servlet:
    multipart:
      max-file-size: 20240MB
      max-request-size: 20240MB
      location: /tmp/run.halo.app
management:
  endpoints:
    web:
      base-path: /api/admin/actuator
      exposure:
        include: ['httptrace', 'metrics','env','logfile','health']
logging:
  level:
    run.halo.app: INFO
    org.eclipse.jetty.server.HttpChannel: ERROR
  file:
    path: ${user.home}/.halo/logs

springfox:
  documentation:
    enabled: true

halo:
  download-timeout: 10m
  cache: memory
  
